- name: set fact to collections list
  set_fact:
    collections: "{{ ccpc.collection | default([]) }}"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_ccpc_cli.yml
  loop: "{{ collections | batch(ccpc.batch_size) | list }}"
