- name: set fact to collections list
  set_fact:
    collections: "{{ ccdm.collection | default([]) }}"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_ccdm_cli.yml
  loop: "{{ collections | batch(ccdm.batch_size) | list }}"
