- name: create {{ role_name }} log directory
  import_tasks: create_logdir.yml
  delegate_to: localhost

- name: show {{ role_name }} inventory
  import_tasks: inventory.yml

- name: Get {{ role_name }} logs
  import_tasks: openstack_cli.yml
