- name: set fact to collections list
  set_fact:
    collections: "{{ smf.collection | default([]) }}"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_smf_cli.yml
  loop: "{{ collections | batch(smf.batch_size) | list }}"

- name: set fact to collections list
  set_fact:
    collections: "{{ smf.collection_yang | default([]) }}"
  when: pod == "n280"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_smf_cli.yml
  loop: "{{ collections | batch(smf.batch_size) | list }}"
