- name: set fact to collections list
  set_fact:
    collections: "{{ ccrc.collection | default([]) }}"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_ccrc_cli.yml
  loop: "{{ collections | batch(ccrc.batch_size) | list }}"
