- hosts: smf
  gather_facts: no
  vars_files:
  - '../../config/collection/common/smf.yaml'
  vars:
    collected_pod: "{{ collected_pod | default('null') }}"
    collected_cluster: "{{ collected_cluster | default('null') }}"
  roles:
  - role: smf
    when:
    - collected_pod | length == 0 and collected_cluster | length == 0
    - pod in parameters.collected_clusters.keys()
    - cluster in parameters.collected_clusters[pod]
    tags:
    - before
    - after
  - role: smf
    when:
    - collected_pod | length != 0 or collected_cluster | length != 0
    - pod == collected_pod or collected_pod | length == 0
    - cluster == collected_cluster or collected_cluster | length == 0
    tags:
    - before
    - after

