- name: set fact to collections list
  set_fact:
    collections: "{{ pcg.collection | default([]) }}"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_pcg_cli.yml
  loop: "{{ collections | batch(pcg.batch_size) | list }}"
