- name: set fact to collections list
  set_fact:
    collections: "{{ cces.collection | default([]) }}"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_cces_cli.yml
  loop: "{{ collections | batch(cces.batch_size) | list }}"
