- name: set fact to collections list
  set_fact:
    collections: "{{ sc.collection | default([]) }}"

- name: Run items asynchronously in batch of five items
  vars:
    durations: "{{ item }}"
  include_tasks: execute_sc_cli.yml
  loop: "{{ collections | batch(sc.batch_size) | list }}"
