- name: Retrieve Junos OS version
  junipernetworks.junos.junos_command:
    commands: show version
  when: ansible_network_os == 'junipernetworks.junos.junos'
  register: show_output
#- debug: msg={{ show_output }}
- name: Write output to log file
  local_action:
    module: copy
    content: "{{ show_output.stdout[0] }}\n"
    dest: "{{ logdir }}/{{ inventory_hostname }}_{{ role_name }}_show_version.log"
    mode: "0664"
    group: "{{ global.logdir_user_group }}"
